### ISSUE TITLE
thread 'blkfiles_parser' panicked 

### ISSUE THREAD

**Issue by axengine** [Blockstream/electrs#126]
electrs running on bitcoin testnet3,thread 'blkfiles_parser' panicked.

```
TRACE writing 0 rows to RocksDB { path: "./db/testnet/newindex/txstore" }, flush=Disable
TRACE reading "/wallet/bitcoin/data-test/testnet3/blocks/blk00075.dat"
TRACE parsing 134202956 bytes
TRACE fetched 0 blocks
TRACE writing 0 rows to RocksDB { path: "./db/testnet/newindex/txstore" }, flush=Disable
TRACE reading "/wallet/bitcoin/data-test/testnet3/blocks/blk00076.dat"
TRACE parsing 134196806 bytes
thread 'blkfiles_parser' panicked at src/new_index/fetch.rs:224:27:
range end index 1162421924 out of range for slice of length 134196806
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/slice/index.rs:76:5
   3: core::slice::index::slice_end_index_len_fail
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/slice/index.rs:68:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

branch:new-index
lastcommit:dca8c5996a4b69e1544a481e1809d0deaf54c771

cargo 1.75.0
Electrum Rust Server 0.4.1
Linux node-public-test-bitcoin-0 6.8.0-1015-gcp #17~22.04.1-Ubuntu SMP Tue Sep  3 16:11:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
clang -v:
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64

OS:Ubuntu 22.04.5 LTS
CPU:Intel(R) Xeon(R) CPU @ 2.20GHz
4Core CPU+16G MEM

**Comment by atylee29** [comment]
I experienced this on my Mac M1 and linux machine as well. Seems electrs has trouble parsing the blk files. My workaround is to run electrs with `--jsonrpc-import` but it is (much?) slower.

**Comment by philippem** [comment]
It will be slower for the initial sync (how much did you experience?)
however once electrs is synced, it always uses json rpc imports.

**Comment by philippem** [comment]
Closing, please use `--jsonrpc-import`.  The initial sync will be slower but after will be fine. We use this mode in production.
